"use client";

import Image from "next/image";
import { useState } from "react";
import { contactFaqs } from "@/data/mock/contact";
import { offices } from "@/data/mock/contact";
import { Button } from "@/components/ui/Button";
import { SectionHeading } from "../shared/SectionHeading";
import { FaqToggleIcon } from "../shared/FaqToggleIcon";

const handleLeadSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
  event.preventDefault();
  const form = event.currentTarget;
  const data = new FormData(form);
  const pesan = String(data.get("message") ?? "");
  const topic = String(data.get("topic") ?? "");
  const bisnis = String(data.get("bisnis") ?? "");
  const email = String(data.get("email") ?? "");
  const res = await fetch("/api/leads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ nama: String(data.get("nama") ?? ""), kontak: String(data.get("whatsapp") ?? "") || email, pesan: `[${topic}] ${bisnis} — ${pesan}`, sourcePage: "/kontak" }) });
  if (res.ok) { alert("Terima kasih! Tim kami akan menghubungi Anda dalam 1x24 jam."); form.reset(); } else { alert("Gagal mengirim. Silakan coba lagi."); }
};

const topics = ["Laporan Perpajakan & Keuangan Bulanan", "Laporan SPT Tahunan Badan (1771) / Orang Pribadi", "Pengurusan PKP & e-Faktur DJP", "Pengurusan EFIN & NPWP Badan", "KAP Audit & Tax Opinion", "Pendampingan Audit, Keberatan & Banding Pajak", "Lainnya"];

export function ContactPage() { const [active, setActive] = useState(0); return <>
  <section className="contact-hero-section"><div className="container"><nav className="contact-breadcrumb"><a href="/"><i className="fa-solid fa-house" /> Beranda</a><span>&gt;</span><strong>Kontak</strong></nav><div className="contact-hero-copy"><div className="hero-tag-pill-figma"><span /> Hubungi Tim EasyTax</div><h1>Mari Bicarakan Kebutuhan <span>Perpajakan &amp; Keuangan</span> Bisnis Anda.</h1><p>Tim kami akan menjelaskan semua yang Anda butuhkan. Pilih cara komunikasi yang paling nyaman untuk Anda.</p></div><div className="quick-contact-grid"><ContactCard icon="fa-brands fa-whatsapp" eyebrow="WHATSAPP · TERCEPAT" title="0811-1920-0080" text="Respons rata-rata kurang dari 5 menit. Tersedia Senin-Jumat, 09:00-17:00 WIB." href="https://mauorder.online/easytaxwebsite" action="Mulai chat WhatsApp" external /><ContactCard icon="fa-regular fa-envelope" eyebrow="EMAIL · FORMAL" title="info@easytax.id" text="Untuk pertanyaan detail, berkas pembukuan, atau dokumen legal. Pesan ditindaklanjuti tim ahli." href="mailto:info@easytax.id" action="Kirim email" /><ContactCard icon="fa-solid fa-phone" eyebrow="TELEPON · KANTOR" title="(021) 2940-0153" text="Hubungi kantor pusat kami. Tim operasional konsultan siap melayani pada jam kerja operasional." href="tel:02129400153" action="Telepon kami" /></div></div></section>
  <section className="contact-form-section"><div className="container"><div className="contact-form-layout"><div className="contact-form-card"><h2>Kirim pertanyaan Anda</h2><p>Isi form berikut dan tim kami akan menghubungi Anda kembali dalam 1×24 jam kerja.</p><hr /><form onSubmit={handleLeadSubmit}><div className="contact-form-row"><Field name="nama" label="Nama Lengkap*" placeholder="Mis. Budi Santoso" required /><Field name="bisnis" label="Nama Bisnis / Perusahaan" placeholder="Mis. PT Maju Bersama" /></div><div className="contact-form-row"><Field name="email" label="Email*" type="email" placeholder="nama@email.com" required /><Field name="whatsapp" label="No. WhatsApp*" type="tel" placeholder="0812-3456-7890" required /></div><label>Topik Konsultasi*<select name="topic" required defaultValue=""><option value="" disabled>Pilih Topik Konsultasi</option>{topics.map((topic) => <option key={topic}>{topic}</option>)}</select></label><label>Pesan / Pertanyaan*<textarea name="message" rows={4} placeholder="Ceritakan kebutuhan perpajakan bisnis Anda — kami akan bantu rekomendasikan solusi yang sesuai." required /></label><p className="privacy-copy">Saya setuju data yang saya kirim akan diproses sesuai <a href="#">Kebijakan Privasi</a> EasyTax.id.</p><button type="submit" className="btn btn-primary btn-lg">Kirim Pertanyaan <i className="fa-solid fa-arrow-right" /></button></form></div><aside className="contact-side-info"><div className="response-card"><i className="fa-solid fa-check" /><div><strong>Respons Cepat</strong><span>Rata-rata kurang dari 5 menit via WhatsApp.</span></div></div><div className="side-card"><h3><i className="fa-regular fa-clock" /> Jam Operasional</h3><p><span>Senin – Jumat</span><strong>09:00 – 17:00</strong></p><p><span>Sabtu</span><strong>09:00 – 13:00</strong></p><p><span>Minggu &amp; Libur</span><strong className="danger">Tutup</strong></p></div><div className="side-card"><h3><i className="fa-solid fa-location-dot" /> Kantor Pusat &amp; Layanan Online</h3><p>Jakarta, Indonesia — Melayani pengusaha &amp; perusahaan di seluruh Indonesia 100% online secara cepat &amp; terproteksi.</p><a href="/tentang-kami">Lihat profil kantor kami <i className="fa-solid fa-arrow-right" /></a></div></aside></div></div></section>
  <section className="offices-section"><div className="container"><SectionHeading title="Layanan Konsultasi Seluruh Indonesia." description="Walaupun proses 100% online & paperless, tim konsultan profesional kami selalu siap mendampingi kebutuhan bisnis Anda." /><div className="offices-grid">{offices.map(([city, address, phone, label, image]) => <article className="office-card" key={city}><div className="office-image"><Image src={`https://images.unsplash.com/${image}?auto=format&fit=crop&w=800&q=80`} alt={`Kantor EasyTax ${city}`} fill sizes="33vw" /><span>{label}</span></div><div className="office-body"><h3><i className="fa-solid fa-location-dot" /> {city}</h3><p>{address}</p></div><div className="office-footer"><span><i className="fa-regular fa-clock" /> Sen~Jum · 09~17</span><strong><i className="fa-solid fa-phone" /> {phone}</strong></div></article>)}</div></div></section>
  <section className="faq-section" id="faq"><div className="container"><SectionHeading badge="FAQ Kontak" title="Pertanyaan yang Sering Diajukan" description="Sebelum menghubungi kami, mungkin jawaban atas pertanyaan Anda ada di bawah ini." /><div className="faq-wrapper">{contactFaqs.map(([question, answer], index) => <div className={`faq-item${active === index ? " active" : ""}`} key={question}><button className="faq-header" onClick={() => setActive(active === index ? -1 : index)}><h3>{question}</h3><FaqToggleIcon open={active === index} /></button>{active === index && <div className="faq-body"><div className="faq-content-inner">{answer}</div></div>}</div>)}</div></div></section>
</>; }

function ContactCard({ icon, eyebrow, title, text, href, action, external = false }: { icon: string; eyebrow: string; title: string; text: string; href: string; action: string; external?: boolean }) { return <article className="quick-contact-card"><div><div className="quick-contact-icon"><i className={icon} /></div><span>{eyebrow}</span><h3>{title}</h3><p>{text}</p></div><a href={href} target={external ? "_blank" : undefined} rel={external ? "noreferrer" : undefined}>{action} <i className="fa-solid fa-arrow-right" /></a></article>; }
function Field({ label, name, placeholder, type = "text", required = false }: { label: string; name?: string; placeholder: string; type?: string; required?: boolean }) { return <label>{label}<input name={name} type={type} placeholder={placeholder} required={required} /></label>; }
