export function MediaTrust() {
  return <section className="trust-section" id="media"><div className="container"><div className="trust-wrapper"><div className="trust-title">Telah Diliput Oleh Media Nasional:</div><div className="media-logos-horizontal">
    <a href="https://www.industry.co.id" target="_blank" rel="noopener noreferrer" className="media-logo-link" title="Industry.co.id"><svg className="media-svg" viewBox="0 0 160 38" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Industry.co.id"><rect x="0" y="7" width="22" height="24" rx="4" fill="#0077C8" /><text x="5" y="24" fontFamily="Outfit, sans-serif" fontWeight="900" fontSize="16" fill="#FFFFFF">i</text><text x="28" y="24" fontFamily="Outfit, sans-serif" fontWeight="800" fontSize="17" fill="#0E1E40" letterSpacing="-0.5">industry</text><text x="104" y="24" fontFamily="Outfit, sans-serif" fontWeight="800" fontSize="14" fill="#0077C8">.co.id</text></svg></a>
    <a href="https://wartaekonomi.co.id" target="_blank" rel="noopener noreferrer" className="media-logo-link" title="Warta Ekonomi"><svg className="media-svg" viewBox="0 0 170 38" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Warta Ekonomi"><text x="0" y="23" fontFamily="Outfit, sans-serif" fontWeight="900" fontSize="17" fill="#C4161C" letterSpacing="-0.5">WARTA</text><text x="76" y="23" fontFamily="Outfit, sans-serif" fontWeight="800" fontSize="17" fill="#0E1E40" letterSpacing="-0.5">EKONOMI</text></svg></a>
    <a href="https://jpnn.com" target="_blank" rel="noopener noreferrer" className="media-logo-link" title="JPNN.com"><svg className="media-svg" viewBox="0 0 135 38" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="JPNN.com"><text x="0" y="24" fontFamily="Outfit, sans-serif" fontWeight="900" fontSize="22" fill="#E52320" letterSpacing="-0.5">JPNN</text><text x="74" y="24" fontFamily="Outfit, sans-serif" fontWeight="800" fontSize="16" fill="#0E1E40">.com</text></svg></a>
    <a href="https://sindonews.com" target="_blank" rel="noopener noreferrer" className="media-logo-link" title="SINDOnews"><svg className="media-svg" viewBox="0 0 155 38" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="SINDOnews"><text x="0" y="23" fontFamily="Outfit, sans-serif" fontWeight="900" fontSize="18" fill="#0E1E40" letterSpacing="-0.5">SINDO</text><text x="72" y="23" fontFamily="Outfit, sans-serif" fontWeight="900" fontSize="18" fill="#E52320" letterSpacing="-0.5">news</text><text x="126" y="23" fontFamily="Outfit, sans-serif" fontWeight="700" fontSize="12" fill="#64748b">.com</text></svg></a>
    <a href="https://businessasia.co.id" target="_blank" rel="noopener noreferrer" className="media-logo-link" title="Business Asia"><svg className="media-svg" viewBox="0 0 160 38" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Business Asia"><text x="0" y="23" fontFamily="Outfit, sans-serif" fontWeight="900" fontSize="16" fill="#0E1E40" letterSpacing="0.5">BUSINESS</text><text x="96" y="23" fontFamily="Outfit, sans-serif" fontWeight="800" fontSize="16" fill="#E5A812" letterSpacing="0.5">ASIA</text></svg></a>
  </div></div></div></section>;
}
